import {webcrypto,createHmac} from 'node:crypto';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import worker,{day,validate,authenticate} from './worker.mjs';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const token='123456:TEST_ONLY_NOT_A_REAL_TOKEN',env={TELEGRAM_BOT_TOKEN:token,STAFF_CHAT_ID:'-100123456'};
let calls=[],fail=false,wrong=false,denied=false;
globalThis.fetch=async(url,options)=>{const method=url.split('/').pop();calls.push({method,body:JSON.parse(options.body)});return new Response(JSON.stringify({ok:!fail,result:method==='getMe'?{id:123456,username:wrong?'OtherBot':'SmartLoanCambodiabot'}:method==='getChat'?{type:'supergroup'}:method==='getChatMember'?{status:denied?'kicked':'member'}:true}),{status:fail?403:200});};
const req=(path,data,headers={})=>new Request('https://example.workers.dev'+path,{method:'POST',headers:{origin:'https://example.workers.dev','content-type':'application/json',...headers},body:JSON.stringify(data)});
const secret=createHmac('sha256',token).update('webhook').digest('hex');
const sign=(age=0)=>{const p=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)-age),user:JSON.stringify({id:111,username:'test_user'})});p.sort();const k=createHmac('sha256','WebAppData').update(token).digest();p.set('hash',createHmac('sha256',k).update([...p].map(([k,v])=>`${k}=${v}`).join('\n')).digest('hex'));return p.toString();};
const data={name:'Test',phone:'+855 12345678',location:'Test area',customerType:'employee',amount:'100',purpose:'Test only',income:'500',duration:'2 years',appointmentDate:day(1),appointmentTime:'09:00–12:00',note:'Line one\nLine two',language:'zh',consent:true,initData:sign()};
let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name)}
await test('valid Telegram signature',async()=>assert.equal((await authenticate(sign(),token)).id,111));
await test('tampered and expired signatures rejected',async()=>{await assert.rejects(authenticate(sign()+'x',token));await assert.rejects(authenticate(sign(7300),token))});
await test('multiline notes accepted',()=>assert.equal(validate({...data}).note,data.note));
await test('invalid phone, amount, past date, missing consent rejected',()=>{for(const patch of [{phone:'-------'},{amount:'-1'},{appointmentDate:day(-1)},{consent:false}])assert.throws(()=>validate({...data,...patch}))});
await test('token-only setup returns pending and registers webhook',async()=>{calls=[];const d=await (await worker.fetch(req('/setup',{}, {authorization:'Bearer '+token}),{TELEGRAM_BOT_TOKEN:token})).json();assert.equal(d.pending,true);assert(calls.some(x=>x.method==='setWebhook'));assert(!calls.some(x=>x.method==='setChatMenuButton'))});
await test('unauthorized setup makes no Telegram calls',async()=>{calls=[];assert.equal((await worker.fetch(req('/setup',{}),env)).status,401);assert.equal(calls.length,0)});
await test('wrong bot rejected before changing webhook',async()=>{calls=[];wrong=true;const d=await (await worker.fetch(req('/setup',{}, {authorization:'Bearer '+token}),env)).json();wrong=false;assert.equal(d.error,'wrong_bot');assert(!calls.some(x=>x.method==='setWebhook'))});
await test('full setup checks group membership and sets menu',async()=>{calls=[];const d=await (await worker.fetch(req('/setup',{}, {authorization:'Bearer '+token}),env)).json();assert.equal(d.link,'https://t.me/SmartLoanCambodiabot?start=apply');assert(calls.some(x=>x.method==='getChatMember'));assert(calls.some(x=>x.method==='setChatMenuButton'))});
await test('bot without group permission rejected',async()=>{denied=true;const d=await (await worker.fetch(req('/setup',{}, {authorization:'Bearer '+token}),env)).json();denied=false;assert.equal(d.error,'chat_permission')});
await test('group chatid command works before staff configured',async()=>{calls=[];await worker.fetch(req('/telegram',{message:{chat:{id:-123,type:'group'},text:'/chatid@SmartLoanCambodiabot'}},{'x-telegram-bot-api-secret-token':secret}),{TELEGRAM_BOT_TOKEN:token});assert.equal(calls[0].body.chat_id,-123);assert(calls[0].body.text.includes('STAFF_CHAT_ID: -123'))});
await test('forged webhook rejected',async()=>assert.equal((await worker.fetch(req('/telegram',{}),env)).status,401));
await test('unconfigured submission rejected',async()=>assert.equal((await worker.fetch(req('/submit',data),{TELEGRAM_BOT_TOKEN:token})).status,503));
await test('cross origin submission rejected',async()=>assert.equal((await worker.fetch(req('/submit',data,{origin:'https://evil.example'}),env)).status,403));
await test('direct web submissions in three languages deliver only to designated staff group',async()=>{for(const language of ['km','en','zh']){calls=[];const direct={...data,language};delete direct.initData;const d=await (await worker.fetch(req('/submit',direct),env)).json();assert.equal(d.ok,true);assert.match(d.ref,/^SF-/);assert.equal(calls.length,1);assert.equal(calls[0].body.chat_id,env.STAFF_CHAT_ID);assert.match(calls[0].body.text,/Source: Web application/)}});
await test('delivery failure never returns success',async()=>{fail=true;assert.equal((await worker.fetch(req('/submit',data),env)).status,502);fail=false});
await test('same request keeps same reference',async()=>{const a=await (await worker.fetch(req('/submit',data),env)).json(),b=await (await worker.fetch(req('/submit',data),env)).json();assert.equal(a.ref,b.ref)});
await test('inline browser scripts parse',async()=>{for(const path of ['/','/setup']){const text=await (await worker.fetch(new Request('https://example.workers.dev'+path),env)).text();for(const m of text.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1])}});
console.log(`${count} checks passed; mocked Telegram only; no real messages or deployment.`);
